a = float(input('INFORME A NOTA "A"\n'))
b = float(input('INFORME A NOTA "B"\n'))
c = float(input('INFORME A NOTA "C"\n'))
media = (a*2+b*3+c*5)/(2+3+5)
media = (round(media,1))
print ('MÉDIA = {}'.format(media))
